# Generated by Django 4.2.15 on 2024-08-21 17:41

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Dentistry', 'Dentistry'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Emergency', 'Emergency'), ('Forensic Pathology', 'Forensic Pathology')], max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('thumbnail', models.ImageField(upload_to='media/departments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=256)),
                ('thumbnail', models.ImageField(upload_to='media/doctors')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=13)),
                ('office_address', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Non binary')], max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(choices=[('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20')], max_length=5)),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('date', 'time_range'), name='unique_date_time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.doctor'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.patient'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.timeslot'),
        ),
        migrations.AddField(
            model_name='patient',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservation.department'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reservation.doctor'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='free_date',
            field=models.ManyToManyField(blank=True, to='Reservation.timeslot'),
        ),
    ]
