# Generated by Django 4.2.15 on 2024-08-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.CharField(default='hi', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.CharField(default='w', max_length=128),
            preserve_default=False,
        ),
    ]
