# Generated by Django 4.2.15 on 2024-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_department_slug_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('d', 'Dentistry'), ('a', 'Anesthesiology'), ('c', 'Cardiology'), ('e', 'Emergency'), ('f', 'Forensic Pathology')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
