# Generated by Django 4.2.15 on 2024-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_department_name_alter_department_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
