# Generated by Django 4.2.15 on 2024-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_alter_department_slug_alter_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Dentistry', 'Dentistry'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Emergency', 'Emergency'), ('Forensic Pathology', 'Forensic Pathology')], max_length=256, unique=True),
        ),
    ]
